######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 6 16:01:47 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += color_wid.h
SOURCES += color_wid.cpp main.cpp
